name = "wan"
main = "src/index.js"
compatibility_date = "2024-09-01"

# AI binding otomatis
[ai]
binding = "AI"

# KV namespace otomatis
[[kv_namespaces]]
binding = "LIMIT_KV"
id = "eb56cc32a181415ab843488e6f547549"
preview_id = "eb56cc32a181415ab843488e6f547549"
